#!/usr/bin/env python3
"""
SID -> PIT (КР580ВИ53) sound converter for Boulder Dash RK86.

Usage:  python3 sid2pit.py > sounds.c

Converts C64 SID frequency registers + ADSR envelopes into
PIT divisor sweeps for the Radio-86RK sound system.

PIT formula:  f_out = PIT_CLK / divisor
SID formula:  f_out = SID_value * 1022900 / 16777216
"""

# --- Config: Radio-86RK PIT clock (CPU 3.55MHz / 2) ---
PIT_CLK = 1_777_000       # Hz — tune this if off-pitch
SID_SCALE = 1_022_900 / 16_777_216  # ≈ 0.06097

def sid_to_hz(sid_reg):
    """Convert 16-bit SID frequency register to Hz."""
    return sid_reg * SID_SCALE

def hz_to_pit(hz):
    """Convert Hz to PIT divisor (integer)."""
    return round(PIT_CLK / hz)

def sweep(base_hz, num_frames, spread=0.15):
    """Generate a PIT divisor sweep around base_hz.
    Start slightly higher pitch (lower divisor), decay to base.
    """
    divs = []
    for i in range(num_frames):
        t = i / (num_frames - 1) if num_frames > 1 else 0
        # Start at base_hz * (1+spread), decay to base_hz
        hz = base_hz * (1 + spread * (1 - t))
        divs.append(hz_to_pit(hz))
    return divs

# ============================================================
# C64 SID sound parameters (from retrointernals.org)
# ============================================================

sounds = {
    "SFX_DIAMOND": {
        "desc": "Rockford collects diamond",
        "sid_freq": 0x1478,     # 5240 -> 319.5 Hz
        "wave": "triangle",
        "frames": 4,
        "spread": 0.25,
    },
    "SFX_BOULDER": {
        "desc": "Boulder falls / pushed",
        "sid_freq": 0x0932,     # 2354 -> 143.5 Hz
        "wave": "noise",
        "frames": 2,
        "spread": 0.05,
    },
    "SFX_EXPLODE": {
        "desc": "3x3 explosion",
        "sid_freq": 0x1432,     # 5170 -> 315 Hz
        "wave": "noise",
        "frames": 8,
        "spread": 0.80,         # wide sweep simulates noise rumble
    },
    "SFX_MOVE": {
        "desc": "Rockford walking (space surface)",
        "sid_freq": 0x3500,     # 13568 -> 827 Hz
        "wave": "noise",
        "frames": 2,
        "spread": 0.05,
    },
}

print("// Auto-generated by sid2pit.py — C64 SID -> PIT divisor tables")
print(f"// PIT_CLK = {PIT_CLK} Hz, SID_SCALE = {SID_SCALE:.6f}")
print()
print("#include <stdint.h>")
print()

for name, s in sounds.items():
    hz = sid_to_hz(s["sid_freq"])
    divs = sweep(hz, s["frames"], s["spread"])
    print(f"// {name}: {s['desc']}")
    print(f"//   SID ${s['sid_freq']:04X} = {s['sid_freq']} -> {hz:.1f} Hz ({s['wave']})")
    print(f"//   PIT divisors ({s['frames']} frames):", end="")
    for d in divs:
        print(f" {d} ({PIT_CLK//d} Hz)", end="")
    print()
    print(f"static const uint16_t {name.lower()}_div[{s['frames']}] = {{", end="")
    for i, d in enumerate(divs):
        if i % 4 == 0:
            print("\n    ", end="")
        print(f"{d}, ", end="")
    print("\n};")
    print()

# --- Title music SID -> PIT converter ---
print("// ============================================================")
print("// Title music: convert C64 MusicData bytes to PIT divisors")
print("// MusicData at $5fe8-$60e7: 256 bytes = 128 notes x 2 bytes")
print("// Each note: (freq_lo, freq_hi) little-endian")
print()

music_bytes = [
    0x16,0x22, 0x1D,0x26, 0x22,0x29, 0x25,0x2E,
    0x14,0x24, 0x1F,0x27, 0x20,0x29, 0x27,0x30,
    0x12,0x2A, 0x12,0x2C, 0x1E,0x2E, 0x12,0x31,
    0x20,0x2C, 0x33,0x37, 0x21,0x2D, 0x31,0x35,
    0x16,0x22, 0x16,0x2E, 0x16,0x1D, 0x16,0x24,
    0x14,0x20, 0x14,0x30, 0x14,0x24, 0x14,0x20,
    0x16,0x22, 0x16,0x2E, 0x16,0x1D, 0x16,0x24,
    0x1E,0x2A, 0x1E,0x3A, 0x1E,0x2E, 0x1E,0x2A,
    0x14,0x20, 0x14,0x2C, 0x14,0x1B, 0x14,0x22,
    0x1C,0x28, 0x1C,0x38, 0x1C,0x2C, 0x1C,0x28,
    0x11,0x1D, 0x29,0x2D, 0x11,0x1F, 0x29,0x2E,
    0x0F,0x27, 0x0F,0x27, 0x16,0x33, 0x16,0x27,
    0x16,0x2E, 0x16,0x2E, 0x16,0x2E, 0x16,0x2E,
    0x22,0x2E, 0x22,0x2E, 0x16,0x2E, 0x16,0x2E,
    0x14,0x2E, 0x14,0x2E, 0x14,0x2E, 0x14,0x2E,
    0x20,0x2E, 0x20,0x2E, 0x14,0x2E, 0x14,0x2E,
    0x16,0x2E, 0x32,0x2E, 0x16,0x2E, 0x33,0x2E,
    0x22,0x2E, 0x32,0x2E, 0x16,0x2E, 0x33,0x2E,
    0x14,0x2E, 0x32,0x2E, 0x14,0x2E, 0x33,0x2E,
    0x20,0x2C, 0x30,0x2C, 0x14,0x2C, 0x31,0x2C,
    0x16,0x2E, 0x16,0x3A, 0x16,0x2E, 0x35,0x38,
    0x22,0x2E, 0x22,0x37, 0x16,0x2E, 0x31,0x35,
    0x14,0x2C, 0x14,0x38, 0x14,0x2C, 0x14,0x38,
    0x20,0x2C, 0x20,0x33, 0x14,0x2C, 0x14,0x38,
    0x16,0x2E, 0x32,0x2E, 0x16,0x2E, 0x33,0x2E,
    0x22,0x2E, 0x32,0x2E, 0x16,0x2E, 0x33,0x2E,
    0x14,0x2E, 0x32,0x2E, 0x14,0x2E, 0x33,0x2E,
    0x20,0x2C, 0x30,0x2C, 0x14,0x2C, 0x31,0x2C,
    0x2E,0x32, 0x29,0x2E, 0x26,0x29, 0x22,0x26,
    0x2C,0x30, 0x27,0x2C, 0x24,0x27, 0x14,0x20,
    0x35,0x32, 0x32,0x2E, 0x2E,0x29, 0x29,0x26,
    0x27,0x30, 0x24,0x2C, 0x20,0x27, 0x14,0x20,
]

print("// Recalculated PIT divisors for title music (128 notes)")
print("// Compare with current bd_music_1ch[] to verify PIT_CLK")
print("uint16_t bd_music_1ch_calc[128] = {")
for i in range(0, 256, 2):
    lo = music_bytes[i]
    hi = music_bytes[i + 1]
    sid_val = lo + (hi << 8)
    hz = sid_to_hz(sid_val)
    pit = hz_to_pit(hz)
    print(f"    {pit},  // note {i//2:3d}: SID ${sid_val:04X} -> {hz:.1f} Hz")
print("};")
